# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatpm:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chatpm:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chatpm:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chatpm:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatpm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatpm:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

substitutions:
  _REGION: us-central1

images:
  - 'gcr.io/$PROJECT_ID/chatpm:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/chatpm:latest'

options:
  logging: CLOUD_LOGGING_ONLY
