'use client';
import {ComposedChart,Area,Line,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {chartData,chartDefaults,chartSummary,metricInfo,metricFormat,type Screen,type Metric} from '@/lib/analytics';
export default function DynamicChart({screen,reduced}:{screen:Screen;reduced:boolean}){
 const spec=screen.chart||chartDefaults(screen.view),rows=chartData(screen),summary=chartSummary(screen),first=spec.metrics[0];
 if(screen.display==='number')return <div className="an-scalar"><p className="an-kicker">{metricInfo[first].label}</p><div className="an-scalar-value">{metricFormat(first,summary[first])}</div><p className="an-context">September {spec.start}–{spec.end}, 2026 · demo data{first==='growth'&&rows.length>1?' · first-to-last change':''}</p></div>;
 if(screen.display==='table')return <><p className="an-kicker">THE DETAILS</p><h2>{spec.metrics.map(m=>metricInfo[m].label).join(' + ')}, day by day.</h2><p className="an-context">September {spec.start}–{spec.end}, 2026 · demo data</p><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Date</th>{spec.metrics.map(m=><th key={m}>{metricInfo[m].label} ({metricInfo[m].unit})</th>)}{spec.previous&&<th>Previous sales (USD)</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.day}><td>{r.day}</td>{spec.metrics.map(m=><td key={m}>{metricFormat(m,r[m])}</td>)}{spec.previous&&<td>{metricFormat('sales',r.previous)}</td>}</tr>)}</tbody></table></div></>;
 return <><div className="an-result-top"><div><p className="an-kicker">{spec.metrics.map(m=>metricInfo[m].label).join(' + ').toUpperCase()}</p><div className="an-value">{metricFormat(first,summary[first])}</div><p className="an-context">September {spec.start}–{spec.end} · {rows.length} {rows.length===1?'day':'days'} · {first==='growth'?'first-to-last change':'demo data'}</p></div>{spec.metrics.length>1&&<div className="an-insight"><p className="an-kicker">{metricInfo[spec.metrics[1]].label.toUpperCase()}</p><h2 style={{color:metricInfo[spec.metrics[1]].color}}>{metricFormat(spec.metrics[1],summary[spec.metrics[1]])}</h2><p>Separate labeled axes preserve each metric’s units.</p></div>}</div>
 <div className="an-chart" role="img" aria-label={rows.map(r=>`${r.day}: ${spec.metrics.map(m=>`${metricInfo[m].label} ${metricFormat(m,r[m])}`).join(', ')}`).join('; ')}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:20,right:10,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#ffffff0f"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#a4afa6',fontSize:12}}/>{spec.metrics.map((m,i)=><YAxis key={m} yAxisId={m} orientation={i?'right':'left'} width={65} axisLine={false} tickLine={false} tick={{fill:metricInfo[m].color,fontSize:12}} tickFormatter={v=>metricInfo[m].unit==='%'?`${v}%`:metricInfo[m].unit==='USD'?`$${v>=1000?(v/1000)+'k':v}`:v>=1000?(v/1000)+'k':String(v)}/>)}<Tooltip contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}} formatter={(value,name)=>{const m=name==='previous'?'sales':name as Metric;return [metricFormat(m,Number(value)),name==='previous'?'Sales · previous week':metricInfo[m].label];}}/><Legend formatter={v=>v==='previous'?'Sales · previous week':`${metricInfo[v as Metric].label} (${metricInfo[v as Metric].unit})`}/>{spec.previous&&<Line yAxisId="sales" dataKey="previous" stroke="#8b9784" strokeDasharray="5 6" dot={false} isAnimationActive={!reduced}/>}{spec.metrics.map(m=>spec.kind==='bar'?<Bar key={m} yAxisId={m} dataKey={m} fill={metricInfo[m].color} radius={[4,4,0,0]} maxBarSize={60} isAnimationActive={!reduced}/>:spec.kind==='line'?<Line key={m} yAxisId={m} dataKey={m} type="monotone" stroke={metricInfo[m].color} strokeWidth={3} dot={{r:4}} isAnimationActive={!reduced}/>:<Area key={m} yAxisId={m} dataKey={m} type="monotone" stroke={metricInfo[m].color} strokeWidth={3} fill={metricInfo[m].color} fillOpacity={.12} dot={rows.length===1} isAnimationActive={!reduced}/>)}</ComposedChart></ResponsiveContainer></div>
 <p className="an-table-note">{spec.metrics.includes('conversion')?'Conversion = orders ÷ sessions. ':''}{spec.metrics.includes('growth')?'Growth is measured against the preceding available day; September 9 has no baseline. ':''}{spec.previous?'Dashed line: matching days in the previous week. ':''}Ask to change the metric, dates, or chart type.</p></>;
}
