'use client';
import {useEffect,useRef,useState} from 'react';
import {AreaChart,Area,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,ArrowUp,AudioLines,Mic,Square,Volume2,VolumeX,Sparkles,ChartNoAxesCombined,Users,MousePointer2,ChevronRight} from 'lucide-react';
import {GeminiLive} from '@/lib/gemini-live';
import {days,customers,questions,totalSales,totalTraffic,totalOrders,growth,usd,screenTool,transitionScreen,interpretQuestion,analyticsInstructions,analyticsResult,type Screen,type AnalyticsView} from '@/lib/analytics';
import './analytics.css';
export default function Analytics(){
 const [screen,setScreen]=useState<Screen>({view:'sales',details:[]}),[status,setStatus]=useState('off'),[text,setText]=useState(''),[answer,setAnswer]=useState('Your week, in focus. Ask a question to explore the numbers.'),[heard,setHeard]=useState(''),[error,setError]=useState(''),[muted,setMuted]=useState(false),[reduced,setReduced]=useState(false);
 const live=useRef<GeminiLive|null>(null),media=useRef<MediaStream|null>(null),current=useRef(screen),epoch=useRef(0),muteRef=useRef(false);current.current=screen;const view=screen.view;
 function stop(){epoch.current++;live.current?.close();live.current=null;media.current?.getTracks().forEach(t=>t.stop());media.current=null;setStatus('off');}
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');setReduced(q.matches);const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>{q.removeEventListener('change',change);epoch.current++;live.current?.close();media.current?.getTracks().forEach(t=>t.stop());};},[]);
 function execute(args:unknown){const next=transitionScreen(current.current,args);current.current=next;setScreen(next);setError('');return {...analyticsResult(next.view),screen:next};}
 function show(next:AnalyticsView){return execute({mode:'replace',view:next});}
 const executeRef=useRef(execute);executeRef.current=execute;
 const [mcp,setMcp]=useState('Checking on-page MCP');
 useEffect(()=>{const mc=(navigator as any).modelContext||(document as any).modelContext;if(!mc?.registerTool){setMcp('Shared page tools active');return;}const controller=new AbortController();try{Promise.resolve(mc.registerTool({name:screenTool.name,description:screenTool.description,inputSchema:screenTool.parameters,execute:async(args:unknown)=>({content:[{type:'text',text:JSON.stringify(executeRef.current(args))}]})},{signal:controller.signal})).then(()=>setMcp('WebMCP connected')).catch(()=>setMcp('Shared page tools active'));}catch{setMcp('Shared page tools active');}return()=>{controller.abort();mc.unregisterTool?.(screenTool.name);};},[]);
 async function start(){if(live.current)return;const generation=++epoch.current;setStatus('connecting');setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(epoch.current!==generation){stream.getTracks().forEach(t=>t.stop());return;}media.current=stream;let input='',output='';const session=new GeminiLive('gemini-3.8-live',{profile:{instructions:analyticsInstructions+' SCREEN RULES: Call show_analytics with mode replace and a view for NEW topics. For more details, why, breakdowns, or a follow-up about the current slide use mode append and a detail; keep the existing graph. Never replace a graph for a same-topic drilldown. Tool returns current screen and demo dataset.',tool:screenTool,context:()=>({...analyticsResult(current.current.view),screen:current.current}),greeting:'Briefly say: Hi, I’m your Meridian analyst. What would you like to explore? Do not change the screen.'},execute:async(name,args)=>{if(name==='stop_listening'){stop();return {stopped:true};}if(name!=='show_analytics')throw Error('Unknown tool');const a=typeof args==='string'?JSON.parse(args):args;const result=executeRef.current(a);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return result;},status:s=>{if(epoch.current===generation)setStatus(s);},input:s=>{input+=s;output='';setHeard(input);},output:s=>{output+=s;input='';setAnswer(output);},error:s=>{if(epoch.current===generation){stop();setError(s);}},ready:()=>{if(epoch.current===generation)setStatus('listening');},muted:()=>muteRef.current,outputStream:()=>{}});live.current=session;await session.connect(stream);}catch(e){if(epoch.current===generation){stop();setError(e instanceof Error?e.message:'Could not connect. Please try again.');}}}
 function ask(message:string){if(!message.trim())return;setText('');setHeard(message);setError('');if(live.current?.ready){live.current.text(message);setStatus('thinking');return;}const action=interpretQuestion(message,current.current);if(action?.mode==='append'){try{execute(action);setAnswer('I’ve kept the current view and added the supporting detail below. These demo figures show what changed; they do not establish why.');}catch(e){setAnswer(e instanceof Error?e.message:'Detail unavailable');}return;}const q=message.toLowerCase();if(/question|example|help/.test(q)){show('questions');setAnswer('Try one of these questions, or tap the orb to talk with your analyst.');}else if(/user|customer/.test(q)){show('customers');setAnswer('Olivia Chen leads this demo week with $3,840 across 12 orders. Customers are ranked by their weekly spend.');}else if(/traffic|visit|session/.test(q)){show('traffic');setAnswer('74,750 sessions this week. September 15 was the busiest day, with 13,900 sessions.');}else if(/sales|revenue|growth/.test(q)){show('sales');setAnswer(/11/.test(q)?'Sales dipped 3.1% on September 11, from $20,480 to $19,840. This dataset does not tell us why.':`Sales reached ${usd(totalSales)}, up ${growth.toFixed(1)}% against the previous week. September 15 was the strongest day at $32,480.`);}else{setAnswer('This demo covers seven-day sales, traffic, and top customers. Tap the orb for a live conversation, or try one of those topics.');}}
 const sales=view==='sales',traffic=view==='traffic';
 return <div className="analytics-app"><header className="an-top"><a className="an-brand" href="#"><span className="an-mark"><ChartNoAxesCombined size={21}/></span>meridian<span className="an-brand-detail">/ intelligence</span></a><div className="an-top-right"><span className="an-demo">DEMO DATA</span><a className="an-project-label" href="https://decisionos.me/projects/analytics.html">READ THE CASE STUDY ↗</a></div></header>
 <main className="an-main"><div className="an-heading"><div><p className="an-kicker">COMMERCE, IN CONVERSATION</p><h1>Your numbers. <span>A little clearer.</span></h1></div><div className="an-date">09 — 15 SEP 2026<span>7-day demo snapshot · USD</span></div></div>
 <nav className="an-nav" aria-label="Analytics views">{([{id:'sales',label:'Sales',icon:ChartNoAxesCombined},{id:'traffic',label:'Traffic',icon:MousePointer2},{id:'customers',label:'Top customers',icon:Users}] as const).map(item=><button key={item.id} aria-pressed={view===item.id} onClick={()=>ask(item.id==='customers'?'Show me top users':`Show me ${item.id}`)}><item.icon size={16}/>{item.label}</button>)}<button className="an-prompts-toggle" aria-pressed={view==='questions'} onClick={()=>show('questions')}><Sparkles size={15}/> What can I ask?</button></nav>
 <div className={`an-workspace ${screen.details.length?'expanded':''}`}><section className="an-stage" key={view} aria-label={view==='customers'?'Top customers by weekly spend':view==='questions'?'Sample questions':`${view} over seven days`}>
 {(sales||traffic)?<><div className="an-result-top"><div><p className="an-kicker">{sales?'TOTAL SALES':'STORE TRAFFIC'}</p><div className="an-value">{sales?usd(totalSales):totalTraffic.toLocaleString()}<span className="an-unit">{sales?'USD':'sessions'}</span></div><p className="an-context">{sales?<><span className="an-growth"><ArrowUpRight size={16}/>{growth.toFixed(1)}%</span> vs. previous 7 days</>:<>Across your store · September 9–15</>}</p></div><div className="an-insight"><span className="an-insight-label"><Sparkles size={14}/> THE SIGNAL</span><p>{sales?<>A strong finish.<br/><strong>Tuesday brought in {usd(days[6].sales)}.</strong></>:<>Your busiest day was Tuesday.<br/><strong>13,900 sessions came through.</strong></>}</p></div></div>
 <div className="an-chart" role="img" aria-label={days.map(d=>`${d.day}: ${sales?usd(d.sales):d.traffic+' sessions'}`).join('; ')}><ResponsiveContainer width="100%" height="100%">{sales?<AreaChart data={days} margin={{top:20,right:12,left:0,bottom:0}}><defs><linearGradient id="sales-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b7f478" stopOpacity={.24}/><stop offset="100%" stopColor="#b7f478" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ffffff0f"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:'#9da99f',fontSize:12}} dy={12}/><YAxis tickFormatter={v=>`$${v/1000}k`} tickLine={false} axisLine={false} tick={{fill:'#9da99f',fontSize:12}} width={52}/><Tooltip contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}} formatter={(v,name)=>[usd(Number(v)),name==='sales'?'This week':'Previous week']}/><Area dataKey="previous" type="monotone" stroke="#647361" strokeDasharray="5 6" fill="transparent" isAnimationActive={!reduced}/><Area dataKey="sales" type="monotone" stroke="#b7f478" strokeWidth={3} fill="url(#sales-fill)" isAnimationActive={!reduced} animationDuration={1000} activeDot={{r:6,stroke:'#101712',strokeWidth:3}}/></AreaChart>:<BarChart data={days} margin={{top:20,right:12,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#ffffff0f"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:'#9da99f',fontSize:12}} dy={12}/><YAxis tickFormatter={v=>`${v/1000}k`} tickLine={false} axisLine={false} tick={{fill:'#9da99f',fontSize:12}} width={52}/><Tooltip cursor={{fill:'#ffffff05'}} contentStyle={{background:'#202922',border:'1px solid #46513f',borderRadius:12,color:'#fff'}} formatter={v=>[Number(v).toLocaleString(),'Sessions']}/><Bar dataKey="traffic" fill="#9dbaed" radius={[5,5,0,0]} maxBarSize={65} animationDuration={900} isAnimationActive={!reduced}/></BarChart>}</ResponsiveContainer></div>
 <div className="an-chart-footer"><div className="an-legend"><span>{sales?'This week':'Sessions'}</span>{sales&&<span className="an-previous">Previous week</span>}</div><span>{sales?'Revenue before refunds · demo':'Sessions, not unique visitors · demo'}</span></div>
 {sales&&<div className="an-daily">{days.map((d,i)=><div key={d.day}><span>{d.day}</span><strong>{i?`${d.sales>=days[i-1].sales?'+':''}${((d.sales/days[i-1].sales-1)*100).toFixed(1)}%`:'—'}</strong><small>{i?'day over day':'baseline'}</small></div>)}</div>}
 </>:view==='customers'?<><div className="an-result-top"><div><p className="an-kicker">THE PEOPLE BEHIND THE NUMBERS</p><h2>Your top customers.</h2><p className="an-context">Ranked by spend · September 9–15 · demo profiles</p></div><span className="an-table-count">TOP 05</span></div><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Rank</th><th>Customer</th><th>Orders</th><th>Sales</th><th>Contribution</th></tr></thead><tbody>{customers.map((c,i)=><tr key={c.name}><td className="an-rank">0{i+1}</td><td><div className="an-person"><span className="an-avatar">{c.initials}</span><div><strong>{c.name}</strong><span>{c.location}</span></div></div></td><td>{c.orders}</td><td className="an-spend">{usd(c.spend)}</td><td><div className="an-meter"><i style={{width:`${c.spend/customers[0].spend*100}%`}}/></div></td></tr>)}</tbody></table></div><p className="an-table-note">These five customers account for {usd(customers.reduce((s,c)=>s+c.spend,0))} in sales this week.</p></>:<><p className="an-kicker">FOLLOW YOUR CURIOSITY</p><h2>Start with a question.</h2><p className="an-context">Say it out loud, type it, or choose one below.</p><div className="an-questions">{questions.map((q,i)=><button onClick={()=>ask(q)} key={q}><span>0{i+1}</span>{q}<ArrowUpRight size={23}/></button>)}</div></>}
 </section>{screen.details.length>0&&<aside className="an-details" aria-label="Additional information">{screen.details.map(detail=><article key={detail} className="an-detail-card"><div className="an-detail-title"><div><p className="an-kicker">ADDED TO THIS VIEW</p><h3>{detail==='comparison'?'The previous week, side by side':detail==='conversion'?'From sessions to orders':view==='customers'?'Customer spending breakdown':'A closer look at each day'}</h3></div><button aria-label={`Dismiss ${detail} detail`} onClick={()=>{const next={...current.current,details:current.current.details.filter(d=>d!==detail)};current.current=next;setScreen(next);}}>×</button></div><div className="an-table-wrap"><table className="an-detail-table"><thead><tr><th>{view==='customers'?'Customer':'Day'}</th><th>{detail==='conversion'?'Sessions':view==='customers'?'Spend':view==='traffic'?'Sessions':'Sales'}</th><th>{detail==='comparison'?'Previous week':detail==='conversion'?'Orders':view==='customers'?'Orders':'Daily growth'}</th><th>{detail==='comparison'?'Change':detail==='conversion'?'Conversion':view==='customers'?'Avg. order':view==='traffic'?'Orders':'Sessions'}</th></tr></thead><tbody>{view==='customers'?customers.map(c=><tr key={c.name}><td>{c.name}</td><td>{usd(c.spend)}</td><td>{c.orders}</td><td>{usd(c.spend/c.orders)}</td></tr>):days.map((d,i)=><tr key={d.day}><td>{d.day}</td><td>{detail==='conversion'||view==='traffic'?d.traffic.toLocaleString():usd(d.sales)}</td><td>{detail==='comparison'?usd(d.previous):detail==='conversion'?d.orders:i?`${(((view==='traffic'?d.traffic/days[i-1].traffic:d.sales/days[i-1].sales)-1)*100).toFixed(1)}%`:'—'}</td><td>{detail==='comparison'?`${((d.sales/d.previous-1)*100).toFixed(1)}%`:detail==='conversion'?`${(d.orders/d.traffic*100).toFixed(2)}%`:view==='traffic'?d.orders:d.traffic.toLocaleString()}</td></tr>)}</tbody></table></div><p className="an-table-note">{detail==='conversion'?'Conversion = orders ÷ sessions.':detail==='comparison'?'Each date is compared with the corresponding day in the previous week.':'Illustrative data. Changes alone do not establish a cause.'}</p></article>)}</aside>}</div><div className="an-bottom"><span>MERIDIAN / DEMO STORE · {mcp}</span><span>{totalOrders.toLocaleString()} orders <span className="an-separator">/</span> {usd(totalSales/totalOrders)} avg. order <span className="an-separator">/</span> {(totalOrders/totalTraffic*100).toFixed(2)}% conversion</span></div>
 <section className="an-assistant" aria-label="Live analyst"><button className={`an-orb ${status}`} onClick={()=>status==='off'?void start():stop()} aria-label={status==='off'?'Start live voice analyst':'Stop live voice analyst'}><span className="an-orb-core"/>{status==='off'?<Mic size={23}/>:status==='connecting'?<AudioLines size={23}/>:<Square size={19}/>}</button><div className="an-conversation"><div className="an-voice-label">{status==='off'?'YOUR LIVE ANALYST':status.toUpperCase()}<span>Gemini 3.8 Live</span></div><p aria-live="polite">{answer}</p>{heard&&<small>You: {heard}</small>}{error&&<p role="alert" className="an-error">{error} You can still explore using the questions or text box.</p>}<form onSubmit={e=>{e.preventDefault();ask(text);}}><input aria-label="Ask your analytics question" placeholder="Ask your numbers anything…" value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Submit question" disabled={!text.trim()}><ArrowUp size={19}/></button></form></div><button className="an-mute" aria-label={muted?'Unmute analyst':'Mute analyst'} aria-pressed={muted} onClick={()=>{muteRef.current=!muted;setMuted(!muted);live.current?.mute(!muted);}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></section><div className="an-followups"><button onClick={()=>ask("Show me more details")}>More details <ArrowUpRight size={14}/></button>{view==='sales'&&<button onClick={()=>ask("Compare with the previous week")}>Compare last week <ArrowUpRight size={14}/></button>}</div><p className="an-footnote">Tap the orb to talk live. Explore the demo with text anytime.<ChevronRight size={12}/></p></main></div>;
}
