'use client';
import {useEffect,useRef,useState} from 'react';
import DynamicChart from './dynamic-chart';
import {ArrowUpRight,ArrowUp,AudioLines,Mic,Square,Volume2,VolumeX,Sparkles,ChartNoAxesCombined,Users,MousePointer2,ChevronRight} from 'lucide-react';
import {GeminiLive} from '@/lib/gemini-live';
import {days as allDays,chartData,chartSummary,metricFormat,screenResult,customers,questions,usd,screenTool,transitionScreen,interpretQuestion,analyticsInstructions,analyticsResult,type Screen,type AnalyticsView} from '@/lib/analytics';
import './analytics.css';
export default function Analytics(){
 const [screen,setScreen]=useState<Screen>({view:'sales',details:[]}),[status,setStatus]=useState('off'),[text,setText]=useState(''),[answer,setAnswer]=useState('Your week, in focus. Ask a question to explore the numbers.'),[heard,setHeard]=useState(''),[error,setError]=useState(''),[muted,setMuted]=useState(false),[reduced,setReduced]=useState(false);
 const live=useRef<GeminiLive|null>(null),media=useRef<MediaStream|null>(null),current=useRef(screen),epoch=useRef(0),muteRef=useRef(false);current.current=screen;const view=screen.view;const days=chartData(screen);const {sales:totalSales,traffic:totalTraffic,orders:totalOrders}=chartSummary(screen);
 function stop(){epoch.current++;live.current?.close();live.current=null;media.current?.getTracks().forEach(t=>t.stop());media.current=null;setStatus('off');}
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');setReduced(q.matches);const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>{q.removeEventListener('change',change);epoch.current++;live.current?.close();media.current?.getTracks().forEach(t=>t.stop());};},[]);
 function execute(args:unknown){const next=transitionScreen(current.current,args);current.current=next;setScreen(next);setError('');return screenResult(next);}
 function show(next:AnalyticsView){return execute({mode:'replace',view:next});}
 const executeRef=useRef(execute);executeRef.current=execute;
 const [mcp,setMcp]=useState('Checking on-page MCP');
 useEffect(()=>{const mc=(navigator as any).modelContext||(document as any).modelContext;if(!mc?.registerTool){setMcp('Shared page tools active');return;}const controller=new AbortController();try{Promise.resolve(mc.registerTool({name:screenTool.name,description:screenTool.description,inputSchema:screenTool.parameters,execute:async(args:unknown)=>({content:[{type:'text',text:JSON.stringify(executeRef.current(args))}]})},{signal:controller.signal})).then(()=>setMcp('WebMCP connected')).catch(()=>setMcp('Shared page tools active'));}catch{setMcp('Shared page tools active');}return()=>{controller.abort();mc.unregisterTool?.(screenTool.name);};},[]);
 async function start(){if(live.current)return;const generation=++epoch.current;setStatus('connecting');setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(epoch.current!==generation){stream.getTracks().forEach(t=>t.stop());return;}media.current=stream;let input='',output='',visualized=false;const session=new GeminiLive('gemini-3.8-live',{profile:{instructions:analyticsInstructions,tool:screenTool,context:()=>screenResult(current.current),greeting:'Briefly say: Hi, I’m your Meridian analyst. What would you like to explore? Do not change the screen.'},execute:async(name,args)=>{if(name==='stop_listening'){stop();return {stopped:true};}if(name!=='show_analytics')throw Error('Unknown tool');const a=typeof args==='string'?JSON.parse(args):args;const result=executeRef.current(a);visualized=true;await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return result;},status:s=>{if(epoch.current===generation)setStatus(s);},input:s=>{if(!input)visualized=false;input+=s;output='';setHeard(input);},complete:()=>{if(input&&!visualized)paint(input);input='';visualized=false;},output:s=>{output+=s;setAnswer(output);},error:s=>{if(epoch.current===generation){stop();setError(s);}},ready:()=>{if(epoch.current===generation)setStatus('listening');},muted:()=>muteRef.current,outputStream:()=>{}});live.current=session;await session.connect(stream);}catch(e){if(epoch.current===generation){stop();setError(e instanceof Error?e.message:'Could not connect. Please try again.');}}}
 function paint(message:string){try{const action=interpretQuestion(message,current.current);if(action){executeRef.current(action);return;}executeRef.current({mode:'replace',display:'table',notice:'I could not match that request to the demo data.'});}catch(e){executeRef.current({mode:'replace',display:'table',notice:e instanceof Error?e.message:'Unable to show that request.'});}}
 function ask(message:string){if(!message.trim())return;setText('');setHeard(message);setError('');paint(message);if(live.current?.ready){live.current.text(message);setStatus('thinking');return;}setAnswer('Your answer is on screen. Ask another question to replace it.');}

 const sales=view==='sales',traffic=view==='traffic';
 return <div className="analytics-app"><header className="an-top"><a className="an-brand" href="#"><span className="an-mark"><ChartNoAxesCombined size={21}/></span>meridian<span className="an-brand-detail">/ intelligence</span></a><div className="an-top-right"><span className="an-demo">DEMO DATA</span><a className="an-project-label" href="https://decisionos.me/projects/analytics.html">READ THE CASE STUDY ↗</a></div></header>
 <main className="an-main"><div className="an-heading"><div><p className="an-kicker">COMMERCE, IN CONVERSATION</p><h1>Your numbers. <span>A little clearer.</span></h1></div><div className="an-date">{screen.chart?.start||9} — {screen.chart?.end||15} SEP 2026<span>Demo snapshot · USD</span></div></div>
 <div className="an-prompt-row"><button className="an-prompts-toggle" onClick={()=>show('questions')}><Sparkles size={15}/> What can I ask?</button></div>
 <div className={`an-workspace `}><section className="an-stage" key={JSON.stringify(screen)} aria-live="polite" aria-label={view==='customers'?'Top customers by weekly spend':view==='questions'?'Sample questions':`${view} chart`}>
 {screen.notice?<div className="an-scalar"><p className="an-kicker">ABOUT YOUR REQUEST</p><h2>{screen.notice}</h2><p className="an-context">Try sales, traffic, orders, conversion or average order value for September 9–15.</p></div>:(sales||traffic)?<DynamicChart screen={screen} reduced={reduced}/>:view==='customers'?<><div className="an-result-top"><div><p className="an-kicker">THE PEOPLE BEHIND THE NUMBERS</p><h2>Your top customers.</h2><p className="an-context">Ranked by spend · September 9–15 · demo profiles</p></div><span className="an-table-count">TOP 05</span></div><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Rank</th><th>Customer</th><th>Orders</th><th>Sales</th><th>Contribution</th></tr></thead><tbody>{customers.map((c,i)=><tr key={c.name}><td className="an-rank">0{i+1}</td><td><div className="an-person"><span className="an-avatar">{c.initials}</span><div><strong>{c.name}</strong><span>{c.location}</span></div></div></td><td>{c.orders}</td><td className="an-spend">{usd(c.spend)}</td><td><div className="an-meter"><i style={{width:`${c.spend/customers[0].spend*100}%`}}/></div></td></tr>)}</tbody></table></div><p className="an-table-note">These five customers account for {usd(customers.reduce((s,c)=>s+c.spend,0))} in sales this week.</p></>:<><p className="an-kicker">FOLLOW YOUR CURIOSITY</p><h2>Start with a question.</h2><p className="an-context">Say it out loud, type it, or choose one below.</p><div className="an-questions">{questions.map((q,i)=><button onClick={()=>ask(q)} key={q}><span>0{i+1}</span>{q}<ArrowUpRight size={23}/></button>)}</div></>}
 </section></div><div className="an-bottom"><span>MERIDIAN / DEMO STORE · {mcp}</span></div>
 <section className="an-assistant" aria-label="Live analyst"><button className={`an-orb ${status}`} onClick={()=>status==='off'?void start():stop()} aria-label={status==='off'?'Start live voice analyst':'Stop live voice analyst'}><span className="an-orb-core"/>{status==='off'?<Mic size={23}/>:status==='connecting'?<AudioLines size={23}/>:<Square size={19}/>}</button><div className="an-conversation"><div className="an-voice-label">{status==='off'?'YOUR LIVE ANALYST':status.toUpperCase()}<span>Gemini 3.8 Live</span></div><p aria-live="polite">{answer}</p>{heard&&<small>You: {heard}</small>}{error&&<p role="alert" className="an-error">{error} You can still explore using the questions or text box.</p>}<form onSubmit={e=>{e.preventDefault();ask(text);}}><input aria-label="Ask your analytics question" placeholder="Ask your numbers anything…" value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Submit question" disabled={!text.trim()}><ArrowUp size={19}/></button></form></div><button className="an-mute" aria-label={muted?'Unmute analyst':'Mute analyst'} aria-pressed={muted} onClick={()=>{muteRef.current=!muted;setMuted(!muted);live.current?.mute(!muted);}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></section><p className="an-footnote">Tap the orb to talk live. Explore the demo with text anytime.<ChevronRight size={12}/></p></main></div>;
}
