'use client';
import {useEffect,useRef,useState} from 'react';
import DynamicChart from './dynamic-chart';
import {ArrowUpRight,ArrowUp,AudioLines,Mic,Square,Volume2,VolumeX,Sparkles,ChartNoAxesCombined,Users,MousePointer2,ChevronRight} from 'lucide-react';
import {GeminiLive} from '@/lib/gemini-live';
import {days as allDays,chartData,chartSummary,metricFormat,screenResult,customers,questions,usd,screenTool,transitionScreen,interpretQuestion,analyticsInstructions,analyticsResult,type Screen,type AnalyticsView} from '@/lib/analytics';
import './analytics.css';
export default function Analytics(){
 const [screen,setScreen]=useState<Screen>({view:'sales',details:[]}),[status,setStatus]=useState('off'),[text,setText]=useState(''),[answer,setAnswer]=useState('Your week, in focus. Ask a question to explore the numbers.'),[heard,setHeard]=useState(''),[error,setError]=useState(''),[muted,setMuted]=useState(false),[reduced,setReduced]=useState(false);
 const live=useRef<GeminiLive|null>(null),media=useRef<MediaStream|null>(null),current=useRef(screen),epoch=useRef(0),muteRef=useRef(false);current.current=screen;const view=screen.view;const days=chartData(screen);const {sales:totalSales,traffic:totalTraffic,orders:totalOrders}=chartSummary(screen);
 function stop(){epoch.current++;live.current?.close();live.current=null;media.current?.getTracks().forEach(t=>t.stop());media.current=null;setStatus('off');}
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');setReduced(q.matches);const change=()=>setReduced(q.matches);q.addEventListener('change',change);return()=>{q.removeEventListener('change',change);epoch.current++;live.current?.close();media.current?.getTracks().forEach(t=>t.stop());};},[]);
 function execute(args:unknown){const next=transitionScreen(current.current,args);current.current=next;setScreen(next);setError('');return screenResult(next);}
 function show(next:AnalyticsView){return execute({mode:'replace',view:next});}
 const executeRef=useRef(execute);executeRef.current=execute;
 const [mcp,setMcp]=useState('Checking on-page MCP');
 useEffect(()=>{const mc=(navigator as any).modelContext||(document as any).modelContext;if(!mc?.registerTool){setMcp('Shared page tools active');return;}const controller=new AbortController();try{Promise.resolve(mc.registerTool({name:screenTool.name,description:screenTool.description,inputSchema:screenTool.parameters,execute:async(args:unknown)=>({content:[{type:'text',text:JSON.stringify(executeRef.current(args))}]})},{signal:controller.signal})).then(()=>setMcp('WebMCP connected')).catch(()=>setMcp('Shared page tools active'));}catch{setMcp('Shared page tools active');}return()=>{controller.abort();mc.unregisterTool?.(screenTool.name);};},[]);
 async function start(){if(live.current)return;const generation=++epoch.current;setStatus('connecting');setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(epoch.current!==generation){stream.getTracks().forEach(t=>t.stop());return;}media.current=stream;let input='',output='';const session=new GeminiLive('gemini-3.8-live',{profile:{instructions:analyticsInstructions+' Use update for chart type, date range, adding metrics or changing comparisons within the current topic. Use append for supporting details without changing the graph. Use replace for new topics. The chart is dynamic: pass the metrics, kind, start and end requested by the user. Return only grounded observations from tool rows and summary, which match the selected dates. Never claim unsupported periods are shown.',tool:screenTool,context:()=>screenResult(current.current),greeting:'Briefly say: Hi, I’m your Meridian analyst. What would you like to explore? Do not change the screen.'},execute:async(name,args)=>{if(name==='stop_listening'){stop();return {stopped:true};}if(name!=='show_analytics')throw Error('Unknown tool');const a=typeof args==='string'?JSON.parse(args):args;const result=executeRef.current(a);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return result;},status:s=>{if(epoch.current===generation)setStatus(s);},input:s=>{input+=s;output='';setHeard(input);},output:s=>{output+=s;input='';setAnswer(output);},error:s=>{if(epoch.current===generation){stop();setError(s);}},ready:()=>{if(epoch.current===generation)setStatus('listening');},muted:()=>muteRef.current,outputStream:()=>{}});live.current=session;await session.connect(stream);}catch(e){if(epoch.current===generation){stop();setError(e instanceof Error?e.message:'Could not connect. Please try again.');}}}
 function ask(message:string){if(!message.trim())return;setText('');setHeard(message);setError('');if(live.current?.ready){live.current.text(message);setStatus('thinking');return;}try{const action=interpretQuestion(message,current.current);if(!action){setAnswer('Try sales, traffic, orders, conversion, or average order value. You can choose line, area, or bar charts and dates within September 9–15.');return;}const result=execute(action);const next=result.screen;if(action.mode==='append'){setAnswer('I’ve kept the graph and added the supporting detail for the selected dates.');}else if(next.view==='customers'){setAnswer('Customers ranked by spend for the full demo week.');}else if(next.view==='questions'){setAnswer('Choose a question, or ask for a different metric, date range, or chart type.');}else{const metrics=next.chart!.metrics,summary=chartSummary(next);setAnswer(`Showing September ${next.chart!.start}–${next.chart!.end}: ${metrics.map(m=>`${m}: ${metricFormat(m,summary[m])}`).join('; ')}. ${next.chart!.kind} chart.`);}}catch(e){setAnswer(e instanceof Error?e.message:'Unable to show that request.');}}

 const sales=view==='sales',traffic=view==='traffic';
 return <div className="analytics-app"><header className="an-top"><a className="an-brand" href="#"><span className="an-mark"><ChartNoAxesCombined size={21}/></span>meridian<span className="an-brand-detail">/ intelligence</span></a><div className="an-top-right"><span className="an-demo">DEMO DATA</span><a className="an-project-label" href="https://decisionos.me/projects/analytics.html">READ THE CASE STUDY ↗</a></div></header>
 <main className="an-main"><div className="an-heading"><div><p className="an-kicker">COMMERCE, IN CONVERSATION</p><h1>Your numbers. <span>A little clearer.</span></h1></div><div className="an-date">{screen.chart?.start||9} — {screen.chart?.end||15} SEP 2026<span>Demo snapshot · USD</span></div></div>
 <nav className="an-nav" aria-label="Analytics views">{([{id:'sales',label:'Sales',icon:ChartNoAxesCombined},{id:'traffic',label:'Traffic',icon:MousePointer2},{id:'customers',label:'Top customers',icon:Users}] as const).map(item=><button key={item.id} aria-pressed={view===item.id} onClick={()=>ask(item.id==='customers'?'Show me top users':`Show me ${item.id}`)}><item.icon size={16}/>{item.label}</button>)}<button className="an-prompts-toggle" aria-pressed={view==='questions'} onClick={()=>show('questions')}><Sparkles size={15}/> What can I ask?</button></nav>
 <div className={`an-workspace ${screen.details.length?'expanded':''}`}><section className="an-stage" key={view} aria-label={view==='customers'?'Top customers by weekly spend':view==='questions'?'Sample questions':`${view} chart`}>
 {(sales||traffic)?<DynamicChart screen={screen} reduced={reduced}/>:view==='customers'?<><div className="an-result-top"><div><p className="an-kicker">THE PEOPLE BEHIND THE NUMBERS</p><h2>Your top customers.</h2><p className="an-context">Ranked by spend · September 9–15 · demo profiles</p></div><span className="an-table-count">TOP 05</span></div><div className="an-table-wrap"><table className="an-table"><thead><tr><th>Rank</th><th>Customer</th><th>Orders</th><th>Sales</th><th>Contribution</th></tr></thead><tbody>{customers.map((c,i)=><tr key={c.name}><td className="an-rank">0{i+1}</td><td><div className="an-person"><span className="an-avatar">{c.initials}</span><div><strong>{c.name}</strong><span>{c.location}</span></div></div></td><td>{c.orders}</td><td className="an-spend">{usd(c.spend)}</td><td><div className="an-meter"><i style={{width:`${c.spend/customers[0].spend*100}%`}}/></div></td></tr>)}</tbody></table></div><p className="an-table-note">These five customers account for {usd(customers.reduce((s,c)=>s+c.spend,0))} in sales this week.</p></>:<><p className="an-kicker">FOLLOW YOUR CURIOSITY</p><h2>Start with a question.</h2><p className="an-context">Say it out loud, type it, or choose one below.</p><div className="an-questions">{questions.map((q,i)=><button onClick={()=>ask(q)} key={q}><span>0{i+1}</span>{q}<ArrowUpRight size={23}/></button>)}</div></>}
 </section>{screen.details.length>0&&<aside className="an-details" aria-label="Additional information">{screen.details.map(detail=><article key={detail} className="an-detail-card"><div className="an-detail-title"><div><p className="an-kicker">ADDED TO THIS VIEW</p><h3>{detail==='comparison'?'The previous week, side by side':detail==='conversion'?'From sessions to orders':view==='customers'?'Customer spending breakdown':'A closer look at each day'}</h3></div><button aria-label={`Dismiss ${detail} detail`} onClick={()=>{const next={...current.current,details:current.current.details.filter(d=>d!==detail)};current.current=next;setScreen(next);}}>×</button></div><div className="an-table-wrap"><table className="an-detail-table"><thead><tr><th>{view==='customers'?'Customer':'Day'}</th><th>{detail==='conversion'?'Sessions':view==='customers'?'Spend':view==='traffic'?'Sessions':'Sales'}</th><th>{detail==='comparison'?'Previous week':detail==='conversion'?'Orders':view==='customers'?'Orders':'Daily growth'}</th><th>{detail==='comparison'?'Change':detail==='conversion'?'Conversion':view==='customers'?'Avg. order':view==='traffic'?'Orders':'Sessions'}</th></tr></thead><tbody>{view==='customers'?customers.map(c=><tr key={c.name}><td>{c.name}</td><td>{usd(c.spend)}</td><td>{c.orders}</td><td>{usd(c.spend/c.orders)}</td></tr>):days.map((d,i)=><tr key={d.day}><td>{d.day}</td><td>{detail==='conversion'||view==='traffic'?d.traffic.toLocaleString():usd(d.sales)}</td><td>{detail==='comparison'?usd(d.previous):detail==='conversion'?d.orders:d.date>9?`${(view==='traffic'?(d.traffic/allDays[d.date-10].traffic-1)*100:d.growth!).toFixed(1)}%`:'—'}</td><td>{detail==='comparison'?`${((d.sales/d.previous-1)*100).toFixed(1)}%`:detail==='conversion'?`${(d.orders/d.traffic*100).toFixed(2)}%`:view==='traffic'?d.orders:d.traffic.toLocaleString()}</td></tr>)}</tbody></table></div><p className="an-table-note">{detail==='conversion'?'Conversion = orders ÷ sessions.':detail==='comparison'?'Each date is compared with the corresponding day in the previous week.':'Illustrative data. Changes alone do not establish a cause.'}</p></article>)}</aside>}</div><div className="an-bottom"><span>MERIDIAN / DEMO STORE · {mcp}</span><span>{totalOrders.toLocaleString()} orders <span className="an-separator">/</span> {usd(totalSales/totalOrders)} avg. order <span className="an-separator">/</span> {(totalOrders/totalTraffic*100).toFixed(2)}% conversion</span></div>
 <section className="an-assistant" aria-label="Live analyst"><button className={`an-orb ${status}`} onClick={()=>status==='off'?void start():stop()} aria-label={status==='off'?'Start live voice analyst':'Stop live voice analyst'}><span className="an-orb-core"/>{status==='off'?<Mic size={23}/>:status==='connecting'?<AudioLines size={23}/>:<Square size={19}/>}</button><div className="an-conversation"><div className="an-voice-label">{status==='off'?'YOUR LIVE ANALYST':status.toUpperCase()}<span>Gemini 3.8 Live</span></div><p aria-live="polite">{answer}</p>{heard&&<small>You: {heard}</small>}{error&&<p role="alert" className="an-error">{error} You can still explore using the questions or text box.</p>}<form onSubmit={e=>{e.preventDefault();ask(text);}}><input aria-label="Ask your analytics question" placeholder="Ask your numbers anything…" value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Submit question" disabled={!text.trim()}><ArrowUp size={19}/></button></form></div><button className="an-mute" aria-label={muted?'Unmute analyst':'Mute analyst'} aria-pressed={muted} onClick={()=>{muteRef.current=!muted;setMuted(!muted);live.current?.mute(!muted);}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></section><div className="an-followups"><button onClick={()=>ask("Show me more details")}>More details <ArrowUpRight size={14}/></button>{view==='sales'&&<button onClick={()=>ask("Compare with the previous week")}>Compare last week <ArrowUpRight size={14}/></button>}</div><p className="an-footnote">Tap the orb to talk live. Explore the demo with text anytime.<ChevronRight size={12}/></p></main></div>;
}
